### ISSUE TITLE
Vertices visited more than once

### ISSUE THREAD

**Issue by tomatoes-prog** [Kuifje02/vrpy#96] opened 2021-06-03 15:46 UTC
I am working with a CVRPTW with 68 nodes on the Graph, when I try to solve the problem with the package I found that with a time_limit of 300 the Pulp Solver is finding multiple routes where the Nodes are visited more than once. I took a look at the code and I found that the module master_solve_pulp.py in line 281 (Sorry, I dont know how to quote the lines) are the constraints of the master problem:
`
    # Save set covering constraints
              
    self.set_covering_constrs[node] = pulp.LpConstraintVar(
                      "visit_node_%s" % node, pulp.LpConstraintGE, right_hand_term )
`

Where I think the problem is that the constraint is build with greater than Sign, I found that changing  it to EQ _pulp.LpConstraintEQ_ solves the problem but i know that the reason is because of the dual variables in the pricing problem. I dont know if there is a way to solve the column generation with GE constraint and solve the final problem with EQ constraint

**Comment by torressa** [comment] 2021-06-03 16:08
Hey again @tomatoes-prog
I think I did this for convergence, as we are minimising it will always end up with equality.
I didn't think about early termination though

Your suggestion makes sense, since the constraints are already saved when calling `_solve(relax=False)` (to get an integer solution at the end), we can change the `sense` parameter of the constraints. e.g. 

```python
def _solve(self, relax: bool, time_limit: Optional[int]):
    if not relax:
        for node in self.G.nodes():
            self.set_covering_constrs[node].sense = pulp.LpConstraintEQ
    # do other stuff        
```

**Comment by tomatoes-prog** [comment] 2021-06-03 16:45
I would like to know if the change of the sign does modify the dual variables and thus the reduced cost function in the pricing problem.

**Comment by torressa** [comment] 2021-06-03 16:51
I don't think so, nope

**Comment by Kuifje02** [comment] 2021-06-03 17:03
I agree with everything @torressa said : 
0/ having a `>=` sign speeds up convergence during the column generation process
1/ the change of sign has no impact on the dual variables 
2/ when solving the last MIP (after the column generation procedure), it should indeed be a `=` sign, as it was before

**Comment by tomatoes-prog** [comment] 2021-06-03 17:18
Perfect! 
Changing it  it to `=` with pulp.LpConstraintEQ decreased the convergence performance.

I will try this myself, I dont know how to publish and share if it works but I will pay attention for future releases if this is fixed. Thank you.

**Comment by torressa** [comment] 2021-06-03 17:20
@Kuifje02 My bad, I'll fix 2 that now
@tomatoes-prog I'll commit to the `dev` branch so you can check it out for now. If you want to contribute you can simply fork it and send a pull request.

**Comment by Kuifje02** [comment] 2021-06-03 17:24
@tomatoes-prog maybe on some specific data set, using a `=` sign speeds up convergence, but in general, it is better to use the `>=` sign while generating columns, so that the dual variables remain positive.

**Comment by tomatoes-prog** [comment] 2021-06-04 17:16
I tried to install it from dev branch but i got the next error

 FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

It seems like the setup.py file is calling a file that doesnt exist in the repo, i am trying this with:

`
pip install git+https://github.com/Kuifje02/vrpy.git@dev
`

Can you suggest me how to try it myself?

**Comment by tomatoes-prog** [comment] 2021-06-04 19:06
@torressa Hello again, I just took a look to the dev branch and tried the previus problem but I still couldn't solve the problem.

I think the problem now is the _solve function still is not working correctly at the last iteration even with  the for loop to change the sense of the constraint because it just modify the LpConstraint object but doesn't modify the Master Problem. I would like to suggets the next piece of code after the not relax conditional

```python
            for const in self.prob.constraints:
                self.prob.constraints[const].sense = pulp.LpConstraintEQ
```


This will modify the sense of the problem but I dont know if this have other consequences

**Comment by Kuifje02** [comment] 2021-06-04 19:47
@tomatoes-prog as mentioned above, doing what you propose will slow down the convergence, as it will allow dual variables to be negative, making the search space of the subproblem larger. 

Can you post a data set (if possible small), so that we can 1/ reproduce the error 2/ fix it 3/ add a unit test  ?

**Comment by tomatoes-prog** [comment] 2021-06-04 20:18
Sorry maybe I am not very clear, and my English is not good. What I am proposing is to modify the constraint after the column generation procedure, like @Kuifje02 proposed some replies ago, so you don't slow the convergence. What I noted was that the commit attempted to solve the problem with this method but It doesnt work because it doesn't modify the `self.prob ` so in the last iteration when you solve the master problem the problem continues with `>=` sense. 

Unfortunately I just reverted the version because this seems to work stable and I cannot show the results. You can try It yourself printing the constraints when change the self.relax object to false:


![image](https://user-images.githubusercontent.com/72456255/120857306-a285ea80-c546-11eb-9edc-14bb128b5157.png)


So, again I propose to change this 
```python
def _solve(self, relax: bool, time_limit: Optional[int]):
    if not relax:
        print(self.prob.constraints)
        for node in self.G.nodes():
            self.set_covering_constrs[node].sense = pulp.LpConstraintEQ
    # do other stuff        

```

for this:
```python

def _solve(self, relax: bool, time_limit: Optional[int]):
    if not relax:
        print(self.prob.constraints)
        #SOLVING THE MIP PROBLEM
        for const in self.prob.constraints:
                #Modify the self.prob object instead of the self.set_covering_constrs object
                self.prob.constraints[const].sense = pulp.LpConstraintEQ
    # do other stuff        
```

![image](https://user-images.githubusercontent.com/72456255/120857890-951d3000-c547-11eb-9f2f-c4cac9cc9f55.png)

You can try this with the any problem you have, even with the docs example, let me know if this doesnt work for you and I will upload a little graph to test

**Comment by Kuifje02** [comment] 2021-06-05 19:56
@tomatoes-prog you are right, for some reason, `self.set_covering_constrs[node].sense = pulp.LpConstraintEQ` does not change the sign.

**Comment by Kuifje02** [comment] 2021-06-05 20:18
Closing for now, will make a new release tomorow. Thanks @tomatoes-prog !

**Closed by Kuifje02** 2021-06-05 20:18 UTC
Labels: invalid
