### ISSUE TITLE
Infeasible problem with time limit, num_vehicles=1 and drop_penalty

### ISSUE THREAD

**Issue by mdubil15** [Kuifje02/vrpy#106] opened 2021-07-12 15:52 UTC
[graphe_vrp.zip](https://github.com/Kuifje02/vrpy/files/6802621/graphe_vrp.zip)

Hello, here is the graph and the issue related. Thanks for your help ;)

With this graph (20 nodes all related to each other and to the source and sink, service_time on each node, and cost=time on each edge) ,
```
prob = VehicleRoutingProblem(graphe_l, num_vehicles = 1, drop_penalty=100, duration = 420)
prob.solve()
```
gives the exception "problem infeasible" though it should show the best routing that one vehicle can operate in less than 420 time units ?

**Comment by Kuifje02** [comment] 2021-07-13 07:21
Hi @mdubil15 ! Thanks for reaching out :)

I am able to reproduce the error. This is very strange. It seems to be related to the solver. The error that is thrown is different if I use CPLEX (`prob.solve(solver="cplex")`), and the error differs if I change the solving parameters withing cplex: I get  `'optimal with unscaled infeasibilities'`.

This needs a little investigation. Will get back to you as soon as I can!

**Comment by Kuifje02** [comment] 2021-07-14 15:47
I am investigating and am pretty sure this a scaling issue.

The concept of using both options `num_vehicles=1` and `drop_penalty=100` is perfectly valid. In fact, one of the unit tests tests this : 

https://github.com/Kuifje02/vrpy/blob/96cc5501d05c341cc50f4377d15f27fbf422584a/tests/test_toy.py#L296-L303

**Comment by Kuifje02** [comment] 2021-07-14 16:32
@mdubil15 Ok, quick fix:

Add this to your code before solving (add some fictitious demand): 

```
for v in G.nodes():
    G.nodes[v]["demand"] = 1
```

This fixes the problem here. Can you check if this works for you?

@Kuifje02 need to understand why drop variables are not created without this.

**Comment by Kuifje02** [comment] 2021-07-14 19:28
In the next release, the code will work without having to add fictitious demand. Closing for now.

**Closed by Kuifje02** 2021-07-14 19:28 UTC
Labels: invalid
